version: '3.8'

services:
  discovery:
    container_name: discovery
    image: bshello25/unbound:unbound-discovery
    ports:
      - "8761:8761"
    networks:
      - unbound-network
    restart: always  # 컨테이너 자동 재시작
  gateway:
    container_name: gateway
    image: bshello25/unbound:unbound-gateway
    ports:
      - "80:80"
      - "443:443"  # HTTPS 적용을 위해 추가
    networks:
      - unbound-network
    restart: always  # 컨테이너 자동 재시작
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 마운트
    environment:
      - SERVER_SSL_KEY_STORE=file:/etc/letsencrypt/live/freethebeast.duckdns.org/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=changeit

networks:
  unbound-network:
    external: true  # 이미 생성된 네트워크 사용
